name: BAU_Workflows
on: 
  workflow_dispatch:
    inputs:
      environment_type:
        description: "select the environment"
        required: true
        default: UAT
        type: choice
        options:
          - UAT
          - PROD
      Ticket_no:
        description: "enter ticket number"
        required: true
        type: string
      script_name:
        description: "select the script"
        default: vanitydomain_add
        required: true
        type: choice
        options:
          - vanitydomain-add
          - vanitydomain-del
          - virtualdomain-add
          - virtualdomain-del
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3
      - name: list file
        run: ls
      - name: run the script
        run: ./{{inputs.script_name}}.sh








