name: Run Python test cases
on:
 push:
  branches:
    - main
    - 'feature/**'
  paths:
    - './github/workflows'
 pull_requests:
   types:
     - opened
     - closed
 workflow_dispatch:
jobs:
  my_job1:
    runs-on: ubuntu-latest
    steps:
      - name: get context
        run: echo "${{toJSON(github)}}"
