name: second Workflow
on: workflow_dispatch
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "hello adarsh"
          echo "this is second line"
      - name: print goodbye
        run: echo "goodbye adarsh"


