name: Python test execution
on: workflow_dispatch
jobs:
  my_job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: install pip and requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r python_programs/requirements.txt
      - name: run the python test
        run: python3 -m pytest python_programs/tests/ -v

  
